services:
  - type: web
    name: gestion-notes-backend
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
