services:
  - type: web
    name: gestion-notes-backend
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "false"
